/stories:
  get:
    summary: Get all stories
    parameters:
      - $ref: "#/components/parameters/LanguageParameter"
      - name: owner_id
        in: query
        description: Select only the story belonging to the owner(s) with the specified ID(s).
        example: 3
        schema:
          $ref: "#/components/schemas/ApiIdListParameter"
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StoriesList"

  post:
    summary: Add a new story
    parameters:
      - $ref: "#/components/parameters/LanguageParameter"
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Stories'
    responses:
      '201':
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Stories'
      '403':
        $ref: "#/components/responses/UnauthorizedError"

/stories/{id}:
  get:
    summary: Get a story by ID
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Stories"
      '404':
        $ref: "#/components/responses/NotFoundError"
  put:
    summary: update a story.
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    operationId: updateCStory
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Stories"
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Stories"
      '403':
        $ref: "#/components/responses/UnauthorizedError"
      '404':
        $ref: "#/components/responses/NotFoundError"

  delete:
    summary: delete a Story by id
    operationId: deleteStory
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    responses:
      '200':
        description: Successful request.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SuccessMessageResponse"
      '403':
        $ref: "#/components/responses/UnauthorizedError"
