/gltf/regenerate:
  get:
    summary: (Re-)create a GLTF file from the orientation stored in the database.
    operationId: regenerateGltf
    description: |-
      ## Authorization

      **Required role:** `superadmin`.
    parameters:
      - name: image_id
        in: query
        description: The unique identifier of the image.
        example: 42
        required: true
        schema:
          $ref: "#/components/schemas/ApiId"
    responses:
      "201":
        description: Successful request.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SuccessMessageResponse"
      "401":
        $ref: "#/components/responses/UnauthorizedError"
      "403":
        $ref: "#/components/responses/ForbiddenError"
    security:
      bearerToken: []
