/stories/{story}/chapters:
  post:
    summary: Add a chapter to the db.
    operationId: addChapter
    parameters:
      - name: stories
        in: path
        required: true
        schema:
          type: string
      - $ref: "#/components/parameters/LanguageParameter"
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Chapters"
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Chapters"

      '404':
        $ref: "#/components/responses/NotFoundError"


/stories/{storyId}/chapters/{id}:
  get:
    summary: Retrieve a chapter by ID
    parameters:
      - name: storyId
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Chapters"
      '404':
        $ref: "#/components/responses/NotFoundError"

  put:
    summary: update a chapter.
    parameters:
      - name: storyId
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
    operationId: updateChapter
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Chapters"
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Chapters"

      '404':
        $ref: "#/components/responses/NotFoundError"

  delete:
    summary: Delete a chapter by ID
    operationId: deleteChapter
    parameters:
      - name: storyId
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
    responses:
      '200':
        description: OK
